Featue/concerts
lemade3k-ironhack/moep-client pull request #7
Opened 2021-05-16 10:06 UTC by AnnaTielke

2021-05-16 11:34 UTC, lemade3k requested changes

2021-05-16 11:34 UTC, lemade3k commented on src/components/users/concerts/ConcertDetail.js
> +      concert.stage;
Hier wird nur die Id der Stage angezeigt. Hast du eine Idee, wie wir hier an den Namen kommen? (Können auch gern noch mal zusammen schauen

2021-05-16 11:34 UTC, lemade3k commented on src/components/users/concerts/ConcertDetail.js
> +    concert.stage;
Hier wird nur die Id der Stage angezeigt, jedoch nicht der Name. Hast du eine Idee, wie wir hier an den Namen kommen? Sonst können wir auch noch mal zusammen schauen

2021-05-16 11:37 UTC, lemade3k commented on src/components/users/concerts/ConcertDetail.js
> +              image={concert.image}
Wurde bei dir das image gerendert? Ich sehs leider nicht

2021-05-16 11:41 UTC, lemade3k commented on src/components/users/concerts/ConcertList.js
> +      })}
Hier fehlt noch die id

```suggestion
      {concerts.map((concert, i) => {
        return <ConcertDetail key={i} concert={concert} />;
      })}
```

2021-05-17 09:18 UTC, AnnaTielke commented on src/components/users/concerts/ConcertList.js
> +      })}
done

2021-05-17 09:19 UTC, merged